export const FIND_BRIDGE = 'FIND_BRIDGE';
export const BRIDGE_FOUND = 'BRIDGE_FOUND';
export const BRIDGE_ERROR = 'BRIDGE_ERROR';
export const PAIR_BRIDGE = 'PAIR_BRIDGE';
export const PAIRING_BRIDGE = 'PAIRING_BRIDGE';
export const PAIR_BRIDGE_SUCCESS = 'PAIR_BRIDGE_SUCCESS';
export const PAIR_BRIDGE_ERROR = 'PAIR_BRIDGE_ERROR';
export const GET_IP = 'GET_IP';
