export const GET_DEVICES = 'GET_DEVICES';
export const GET_DEVICES_SUCCESS = 'GET_DEVICES_SUCCESS';
export const GET_GROUP = 'GET_GROUP';
export const GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS';
export const CHANGE_DEVICES_COLOR = 'CHANGE_DEVICES_COLOR';
export const CHANGE_GROUP_COLOR = 'CHANGE_GROUP_COLOR';
